language: cpp
dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - sudo apt update
  - wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel_0.11.1-linux-x86_64.deb
  - sudo dpkg -i bazel_0.11.1-linux-x86_64.deb

script:
  - travis_wait bazel test --test_output=all --action_env="GTEST_COLOR=1" //test/...